# Generated by Django 4.2.4 on 2024-03-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('occurrence_time', models.DateTimeField(help_text='Date and time of the event occurance')),
                ('event_name', models.CharField(help_text='Name of the event', max_length=200)),
                ('id', models.CharField(editable=False, help_text='Event ID', max_length=4, primary_key=True, serialize=False)),
                ('severity', models.CharField(help_text='Severity of the event', max_length=200, null=True)),
            ],
            options={
                'ordering': ['-event_name'],
            },
        ),
        migrations.CreateModel(
            name='Latitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Time stamp of the recorded latitude position')),
                ('position', models.DecimalField(decimal_places=4, help_text='Latitude position', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Longitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Time stamp of the recorded longitude position')),
                ('position', models.DecimalField(decimal_places=4, help_text='Longitude position', max_digits=9)),
            ],
        ),
    ]
